use_frameworks!

target 'HUFramework_Example' do
  pod 'HUFramework', :path => '../'

  target 'HUFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
